export const ERROR_CODE = {
  NOT_LOGIN_LIMIT_EXCEEDED: "NOT_LOGIN_LIMIT_EXCEEDED",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_EXPIRED: "jwt expired",
  INVALID_TOKEN: "INVALID_TOKEN",
};
